# Generated by Django 6.0.5 on 2026-07-12 05:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('provider', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(help_text='Original page we scraped from', unique=True)),
                ('application_url', models.URLField(blank=True, help_text='Direct apply link if different')),
                ('description', models.TextField(blank=True)),
                ('short_summary', models.TextField(blank=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('program_start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('results_out', 'Results Announced'), ('unknown', 'Unknown')], default='open', max_length=20)),
                ('eligible_nationalities', models.JSONField(blank=True, default=list, help_text="List of eligible countries or ['all']")),
                ('eligible_study_levels', models.JSONField(blank=True, default=list, help_text="e.g. ['Bachelors', 'Masters', 'PhD']")),
                ('min_gpa', models.FloatField(blank=True, null=True)),
                ('gpa_scale', models.CharField(blank=True, help_text='e.g. 4.0, 5.0', max_length=20)),
                ('eligible_fields_of_study', models.JSONField(blank=True, default=list, help_text="List of fields or ['any']")),
                ('age_limit_max', models.PositiveIntegerField(blank=True, null=True)),
                ('financial_need_required', models.BooleanField(default=False)),
                ('study_destinations', models.JSONField(blank=True, default=list, help_text='Countries where you can use the scholarship')),
                ('funding_details', models.TextField(blank=True, help_text='What is covered (tuition, stipend, travel...)')),
                ('funding_amount_approx', models.JSONField(blank=True, default=dict, help_text='Structured amount info if available')),
                ('number_of_awards', models.PositiveIntegerField(blank=True, null=True)),
                ('eligibility_details', models.TextField(blank=True)),
                ('required_documents', models.TextField(blank=True)),
                ('selection_criteria', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('notes_for_applicants', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_user_submitted', models.BooleanField(default=False, help_text='Came through public user submission form')),
                ('last_verified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Scholarships',
                'ordering': ['-application_deadline', 'title'],
            },
        ),
    ]
